import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { GoogleAnalytics } from "@next/third-parties/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function AnalyticsProvider() {
  if (
    process.env.ANALYTICS_ENABLED === "true" &&
    process.env.GOOGLE_ANALYTICS_GAID
  ) {
    return <GoogleAnalytics gaId={process.env.GOOGLE_ANALYTICS_GAID} />;
  }
  console.log(
    "[Analytics Provider] Analytics is disabled or you are missing an enviroment variable.",
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* SC 2.4.1 — Skip link: first focusable element, jumps past repeated nav.
            The target #main-content is on the <main> element below. */}
        <a href="#main-content" className="skip-link">
          Skip to main content
        </a>
        <Header />
        {/* SC 1.3.1 — Main landmark: wraps all page content below the header.
            tabIndex={-1} allows the skip link to programmatically focus this
            element in browsers that don't natively focus non-interactive targets. */}
        <main
          id="main-content"
          tabIndex={-1}
          className="flex flex-col flex-1 outline-none"
        >
          {children}
        </main>
      </body>
      <AnalyticsProvider />
    </html>
  );
}
